ALTER TABLE "BugReport"
  ADD COLUMN IF NOT EXISTS "labels" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "branchName" TEXT,
  ADD COLUMN IF NOT EXISTS "dorScore" INTEGER,
  ADD COLUMN IF NOT EXISTS "dorChecklist" JSONB,
  ADD COLUMN IF NOT EXISTS "isReady" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "staticAnalysis" JSONB;